dist: xenial
sudo: required
env:
  global:
    - HUGO_RELEASE=0.62.1
language: node_js # npm is needed to install postcss-cli
node_js: "lts/*"
cache: npm
git:
  depth: 1
install:
  - npm install postcss-cli autoprefixer # Required for hugo's built-in postcss/autoprefixer
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo --environment searchindex
  - bash tools/build_search_index.sh
  - hugo
deploy:
  - provider: pages
    repo: mrascii/scibook
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Personal access token is set in travis-ci.org dashboard, marked secure, see https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line
    keep-history: true
    on:
      branch: master
